name: Deploy PR

on:
  pull_request:
    branches: [ master ]

jobs:
  deployPR:
    name: Deploy PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Publish Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build . -t "habibiefaried/pr-deployment-pipeline:pr-${{ github.event.number }}"
          docker push "habibiefaried/pr-deployment-pipeline:pr-${{ github.event.number }}"

      # https://github.com/appleboy/ssh-action
      - name: Deploy docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo ls -lah /root