name: Deploy PR

on:
  pull_request:
    branches: [ master ]

jobs:
  deployPR:
    name: Deploy PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Publish Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build . -t "habibiefaried/pr-deployment-pipeline:pr-${{ github.event.number }}"
          docker push "habibiefaried/pr-deployment-pipeline:pr-${{ github.event.number }}"

      # https://github.com/appleboy/ssh-action
      - name: Deploy docker
        uses: appleboy/ssh-action@master
        env:
          PRNUM: ${{ github.event.number }}
          VHOST_ADDRESS: ${{ secrets.VHOST_ADDRESS }}
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          envs: PRNUM, VHOST_ADDRESS
          script: |
            PRNUM=$PRNUM envsubst < /etc/caddy/vhost.caddy.template > /tmp/temporary
            sudo cp /tmp/temporary "/etc/caddy/includes/$PRNUM.$VHOST_ADDRESS"
            sudo docker rm -f "pr-deployment-pipeline-$PRNUM" 2>/dev/null
            sudo docker pull habibiefaried/pr-deployment-pipeline:pr-$PRNUM
            sudo docker run --name "pr-deployment-pipeline-$PRNUM" -dit -p "127.0.0.1:4000$PRNUM:80" habibiefaried/pr-deployment-pipeline:pr-$PRNUM
            sudo service caddy restart